version: "3.7"
services:
  app:
    init: true
    build:
      context: .
    command: sleep infinity
    volumes:
      - ..:/app:cached
      - dotconfig:/home/app/.config
      - go:/home/app/go

volumes:
  go:
  dotconfig:
